version: "3"

services:
  app:
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
    build:
      context: .
    ports:
      - 3000:80
    depends_on:
      - pg

  pg:
    image: postgres
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1m"
    ports:
      - 5432:5432
    volumes:
      - ./db/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
